apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dstodeployutilitiesonhostnode
  name: dstodeployutilitiesonhostnode
spec:
  selector:
    matchLabels:
      app: dstodeployutilitiesonhostnode
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dstodeployutilitiesonhostnode
    spec:
      containers:
      - image: nginx
        name: nginx
        securityContext:
            privileged: true        
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -c
          - |
            echo "installing tcp dump utility started"
            sudo apt install tcpdump
            echo "installing tcp dump utility completed "
            sleep 100000s
      restartPolicy: Always
      hostPID: true
